default_line_style:
  type: line
  line:
    width: 2

default_dash_line_style:
  type: line
  line:
    width: 2
    dash: dash
  opacity: 0.7

default_arrow_style:
  showarrow: True
  arrowhead: 2
  arrowsize: 1
  arrowwidth: 2
  xref: x
  axref: x
  yref: y
  ayref: y

default_text_style:
  showarrow: False
  borderpad: 4
  font:
    size: 12

default_small_text_style:
  showarrow: False
  borderpad: 2
  font:
    size: 10

default_circle_style:
  line: 
    width: 2
  type: circle
  layer: above
  xsizemode: pixel
  ysizemode: pixel

default_circle_size:
  circular_radius: 20
  oval_x_width: 32
  oval_y_width: 18

default_circle_text_style:
  borderpad: 2
  showarrow: False
  font:
    size: 12