annotationdefaults: 
  arrowhead: 0
  arrowwidth: 1
autotypenumbers: 'strict'
coloraxis: 
  colorbar: 
    outlinewidth: 1
    tickcolor: 'rgb(36,36,36)'
    ticks: 'outside'
geo:
  # bgcolor: 'white'
  lakecolor: 'white'
  landcolor: 'white'
  showlakes: True
  showland: True
  subunitcolor: 'white'
hoverlabel: 
  align: 'left'
hovermode: 'closest'
mapbox: 
  style: 'light'
paper_bgcolor: "#ffffff"
plot_bgcolor: "#ffffff"
polar: 
  angularaxis: 
    gridcolor: 'rgb(232,232,232)'
    linecolor: 'rgb(36,36,36)'
    showgrid: False
    showline: True
    ticks: 'outside'
    # bgcolor: 'white'
  radialaxis: 
    gridcolor: 'rgb(232,232,232)'
    linecolor: 'rgb(36,36,36)'
    showgrid: False
    showline: True
    ticks: 'outside'
scene: 
  xaxis: 
    backgroundcolor: 'white'
    gridcolor: 'rgb(232,232,232)'
    gridwidth: 2
    linecolor: 'rgb(36,36,36)'
    showbackground: True
    showgrid: False
    showline: True
    ticks: 'outside'
    zeroline: False
    zerolinecolor: 'rgb(36,36,36)'
  yaxis: 
    backgroundcolor: 'white'
    gridcolor: 'rgb(232,232,232)'
    gridwidth: 2
    linecolor: 'rgb(36,36,36)'
    showbackground: True
    showgrid: False
    showline: True
    ticks: 'outside'
    zeroline: False
    zerolinecolor: 'rgb(36,36,36)'
  zaxis: 
    backgroundcolor: 'white'
    gridcolor: 'rgb(232,232,232)'
    gridwidth: 2
    linecolor: 'rgb(36,36,36)'
    showbackground: True
    showgrid: False
    showline: True
    ticks: 'outside'
    zeroline: False
    zerolinecolor: 'rgb(36,36,36)'
shapedefaults: 
  fillcolor: 'black' 
  line: 
    width: 0 
  # opacity: 0.3
ternary: 
  aaxis: 
    gridcolor: 'rgb(232,232,232)'
    linecolor: 'rgb(36,36,36)'
    showgrid: False
    showline: True
    ticks: 'outside'
  baxis: 
    gridcolor: 'rgb(232,232,232)'
    linecolor: 'rgb(36,36,36)'
    showgrid: False
    showline: True
    ticks: 'outside'
  # bgcolor: 'white'
  caxis: 
    gridcolor: 'rgb(232,232,232)'
    linecolor: 'rgb(36,36,36)'
    showgrid: False
    showline: True
    ticks: 'outside'
title: 
  x: 0.05
barcornerradius: 10
bargap: 0.2
xaxis:
  automargin: True
  showgrid: False
  showline: True
  ticks: 'outside'
  title: 
    standoff: 15
  zeroline: False
  rangemode: 'tozero'
yaxis: 
  automargin: True
  showgrid: False
  showline: True
  ticks: 'outside'
  title: 
    standoff: 15
  zeroline: False
  rangemode: 'tozero'
margin:
  t: 70
  l: 20
  r: 20
  b: 20